# frozen_string_literal: true

require "pathname"

module TokenizeAttr
  # Manages the lifecycle of the tokenize_attr initializer inside a Rails app.
  #
  # This class holds all file-system logic so it can be unit-tested without
  # requiring a full Rails boot or Rake DSL. The rake tasks are thin shells
  # that delegate here.
  #
  # @example From a Rake task (or Rails generator):
  #   TokenizeAttr::Installer.install!(Rails.root)
  #   TokenizeAttr::Installer.uninstall!(Rails.root)
  #
  class Installer
    INITIALIZER_PATH = Pathname.new("config/initializers/tokenize_attr.rb")

    INITIALIZER_CONTENT = <<~RUBY
      # frozen_string_literal: true

      # Auto-include TokenizeAttr::Concern into every ActiveRecord model so that
      # the .tokenize macro is available without an explicit include in each class.
      #
      # Generated by: rails tokenize_attr:install
      #
      # To opt out of auto-include, remove this file and add
      #   include TokenizeAttr::Concern
      # to whichever models need it.
      ActiveSupport.on_load(:active_record) do
        include TokenizeAttr::Concern
      end
    RUBY

    # Write the initializer to +rails_root/config/initializers/tokenize_attr.rb+.
    #
    # @param rails_root [Pathname, String] the root directory of the Rails app
    # @return [:created, :skipped]
    def self.install!(rails_root)
      destination = Pathname.new(rails_root).join(INITIALIZER_PATH)

      return :skipped if destination.exist?

      destination.write(INITIALIZER_CONTENT)
      :created
    end

    # Remove the initializer if it exists.
    #
    # @param rails_root [Pathname, String]
    # @return [:removed, :skipped]
    def self.uninstall!(rails_root)
      destination = Pathname.new(rails_root).join(INITIALIZER_PATH)

      return :skipped unless destination.exist?

      destination.delete
      :removed
    end
  end
end
